#!/bin/sh
# convert images or video to gif

help() {
	echo "Convert images or video to gif with ffmpeg"
	echo ""
	echo "USAGE"
	echo "  $ 2gif [options] <src>"
	echo ""
	echo "OPTIONS"
	echo "  -f, --fps           fps"
	echo "  -s, --size          gif dimension"
	echo "  -t, --transparent   remove white background"
	echo "      --fuzz          background remove fuzz"
	echo ""
	echo "EXAMPLE"
	echo "  $ 2gif --size -1:320 --fps 60 cat.mov"
}

die() {
	echo "$1" >&2
	exit 1
}

if [ -z "$1" ]; then
	help
	exit 0
fi

size="-1:240"
fps=30
transparent=0
fuzz=5

while [ -n "$1" ]; do
	case $1 in
		-s|--size)
			if [ -n "$2" ]; then
				size=$2
				shift
			else
				die "-s / --size requires argument"
			fi
		;;
		-f|--fps)
			if [ -n "$2" ]; then
				fps=$2
				shift
			else
				die "-f / --fps requires argument"
			fi
		;;
		-t|--transparent)
			transparent=1
		;;
		--fuzz)
			if [ -n "$2" ]; then
				fuzz=$2
				shift
			else
				die "--fuzz requires argument"
			fi
		;;
		--)
			shift
			break
		;;
		-?*)
			die "unknown option: $1"
		;;
		*)
			break
		;;
	esac
	shift
done

src=$1
name="${src%%.*}"
dest="$name.gif"

if [ $transparent = 1 ]; then
	mkdir .tmp
	ffmpeg -i "$src" .tmp/%04d.png
	cd .tmp || exit
	for f in *.png; do
		magick "$f" -fuzz "$fuzz%" -transparent white "t_$f"
	done
	cd .. || exit
	src=".tmp/t_%04d.png"
fi

ffmpeg \
	-hide_banner \
	-i "$src" \
	-vf "fps=$fps,scale=$size:flags=lanczos,split[s0][s1];[s0]palettegen=max_colors=64[p];[s1][p]paletteuse=dither=bayer:bayer_scale=3" \
	-loop 0 \
	"$dest"

if [ $transparent = 1 ]; then
	rm -rf .tmp
fi
