#!/bin/sh
# convert images or video to gif

help() {
	echo "Convert images or video to gif with ffmpeg"
	echo ""
	echo "USAGE"
	echo "  $ 2gif [options] <src>"
	echo ""
	echo "OPTIONS"
	echo "  -f, --fps      fps"
	echo "  -s, --size     gif dimension"
	echo "  -o, --output   output file name"
	echo ""
	echo "EXAMPLE"
	echo "  $ 2gif --size -1:320 --fps 60 cat.mov"
}

die() {
	echo "$1" >&2
	exit 1
}

ntharg() {
	shift "$1"
	echo "$1"
}

if [ -z "$1" ]; then
	help
	exit 0
fi

src=$(ntharg $# "$@")
size="-1:240"
fps=30
ext=$(echo "${src##*.}" | tr '[:upper:]' '[:lower:]')
name=$(basename "$src" ".$ext")
dest="$name.gif"

while [ -n "$1" ]; do
	case $1 in
		-s|--size)
			if [ -n "$2" ]; then
				size=$2
				shift
			else
				die "-s / --size requires argument"
			fi
		;;
		-f|--fps)
			if [ -n "$2" ]; then
				fps=$2
				shift
			else
				die "-f / --fps requires argument"
			fi
		;;
		-o|--output)
			if [ -n "$2" ]; then
				dest=$2
				shift
			else
				die "-o / --output requires argument"
			fi
		;;
		--)
			shift
			break
		;;
		-?*)
			die "unknown option: $1"
		;;
	esac
	shift
done

ffmpeg \
	-hide_banner \
	-i "$src" \
	-vf "fps=$fps,scale=$size:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
	-loop 0 \
	"$dest"
