#!/bin/sh
# convert video to 480p mp4

src=$1

if [ ! -f "$src" ]; then
	exit
fi

res=${2:-480}
ext=${src##*.}

dest="$(basename "$src" ".$ext")-${res}p.mp4"
ffmpeg -i "$src" -vf scale="-2:$res" -pix_fmt yuv420p "$dest" || exit 1
