#!/usr/bin/env lua

if (not arg[1]) then
	return
end

local file = io.open(arg[1], "r")
local cur_entry = nil
local bookmarks = {}

for l in file:lines() do

	local a, b = l:find(">%w+</H3>")

	if (a and b) then
		cur_entry = l:sub(a + 1, b - 5)
		bookmarks[cur_entry] = {}
	end

	if (cur_entry) then
		local c, d = l:find("HREF=\"[^\"]+")
		if (c and d) then
			table.insert(bookmarks[cur_entry], l:sub(c + 6, d))
		end
	end

end

if (arg[2]) then
	local entries = bookmarks[arg[2]]
	if (entries) then
		for _, p in ipairs(entries) do
			print(p)
		end
	else
		print("no such tag")
	end
else
	for k, v in pairs(bookmarks) do
		print(k .. ":")
		for _, p in ipairs(v) do
			print("  " .. p)
		end
	end
end

