#!/bin/sh
# recursively cat all files

catdir() {
	for f in *; do
		name="$f"
		if [ -n "$1" ]; then
			name="$1/$f"
		fi
		if [ -d "$f" ]; then
			(
				cd "$f" || exit
				catdir "$name"
			)
		elif [ -f "$f" ]; then
			echo "$name"
			echo "-------"
			cat "$f"
			echo ""
		fi
	done
}

catdir
