#!/bin/sh

help() {
	echo "Quickly build and run a c file"
	echo ""
	echo "USAGE"
	echo "  $ ccc <file>"
}

if [ -z "$1" ]
then
	help
	exit 1
fi

name=$(basename "$1" .c)
cc "$name.c" $CFLAGS $LDFLAGS -o "$name" && ./"$name" "${@:2}"
