#!/bin/sh
# convert all files in current dir to another format with ffmpeg

help() {
	echo "Convert all files in current dir to another format with ffmpeg"
	echo ""
	echo "USAGE"
	echo "  $ convert <from> <to>"
	echo ""
	echo "EXAMPLE"
	echo "  $ convert png jpg"
	echo "  $ convert flac mp3"
}

if [ -z "$1" ] || [ -z "$2" ]
then
	help
	exit 1
fi

flags=""

if [ "$2" = "mp3" ]
then
	flags="$flags -ab 256k"
fi

for file in "*.$1"
do
	ffmpeg -i "$file" "$flags" "$(basename "$file" ".$1").$2"
done
