#!/bin/sh
# convert all files in current dir to another format with ffmpeg

help() {
	echo "Convert all files in current dir to another format with ffmpeg"
	echo ""
	echo "USAGE"
	echo "  $ conv <from> <to>"
	echo ""
	echo "EXAMPLE"
	echo "  $ conv png jpg"
	echo "  $ conv flac mp3"
}

from="$1"
to="$2"
flags="$3"

if [ -z "$from" ] || [ -z "$to" ]
then
	help
	exit 1
fi

for file in *."$from"
do
	ffmpeg -i "$file" "$(basename "$file" ".$from").$to"
done
