#!/bin/sh
# download music from youtube playlist

help() {
	echo "Download music from youtube playlist"
	echo ""
	echo "USAGE"
	echo "    $ dalbum <name> <url>"
}

album="$1"
url="$2"

if [ -z "$album" ] || [ -z "$url" ]; then
	help
	exit 1
fi

dir="$HOME/files/todo/listen/$album"
mkdir "$dir"

case "$url" in
	*"list="*)
		(
			cd "$dir" || exit
			yt-dlp \
				-o '%(playlist_index)02d - %(title)s.%(ext)s' \
				-i \
				--yes-playlist \
				-x --audio-format mp3 \
				"$url"
			i=1
			for f in *.mp3; do
				mv "$f" ".b-$f"
				title=$(basename "$f" ".mp3" | cut -c6-)
				ffmpeg \
					-hide_banner \
					-i ".b-$f" \
					-c copy \
					-metadata track="$i" \
					-metadata album="$album" \
					-metadata title="$title" \
					"$f"
				rm ".b-$f"
				i=$((i + 1))
			done
		)
	;;
	*)
		(
			cd "$dir" || exit
			yt-dlp \
				--split-chapters \
				-o '%(chapter_number)02d - %(chapter)s.%(ext)s' \
				-i \
				--no-playlist \
				-x --audio-format mp3 \
				"$url"
			i=1
			for f in *.mp3; do
				mv "$f" ".b-$f"
				title=$(basename "$f" ".mp3" | cut -c6-)
				ffmpeg \
					-hide_banner \
					-i ".b-$f" \
					-c copy \
					-metadata track="$i" \
					-metadata album="$album" \
					-metadata title="$title" \
					"$f"
				rm ".b-$f"
				i=$((i + 1))
			done
		)
	;;
esac

echo "music downloaded to \"$dir\""
