#!/bin/sh

help() {
	echo "Download music from youtube playlist"
	echo ""
	echo "USAGE"
	echo "    $ dalbum <name> <url>"
}

album="$1"
url="$2"

if [ -z "$album" ] || [ -z "$url" ]
then
	help
	exit 1
fi

dir="$HOME/todo/listen/$album"
mkdir "$dir"

case "$url" in
	*"list="*)
		cd "$dir" && \
			yt-dlp \
				--cookies /Users/tga/files/cookies/youtube.txt \
				-x --audio-format mp3 \
				-o '%(title)s.%(ext)s' \
				-i \
				--yes-playlist \
				--postprocessor-args "-metadata album='$album'" "$url"
	;;
	*)
		cd "$dir" && \
			yt-dlp \
				--cookies /Users/tga/todo/listen/cookies.txt \
				-x --audio-format mp3 \
				--split-chapters \
				-o '%(chapter)s.%(ext)s' \
				-i \
				--no-playlist \
				--postprocessor-args "-metadata album='$album'" "$url"
	;;
esac

echo "music downloaded to $dir"
