#!/bin/sh
# concat videos with ffmpeg

echo > .ffconcat.txt

for file in "$@"; do
	ext=${file##*.}
	echo file \'$file\' >> .ffconcat.txt
done

ffmpeg \
	-hide_banner \
	-f concat \
	-i .ffconcat.txt \
	-safe 0 \
	-c copy \
	"ffconcat.$ext"
rm .ffconcat.txt
