#!/bin/sh
# concat videos with ffmpeg

echo > .ffconcat.txt

for file in "$@"
do
	echo file \'$file\' >> .ffconcat.txt
done

ffmpeg -f concat -safe 0 -i .ffconcat.txt -c copy ffconcat.mp4
rm .ffconcat.txt
