#!/usr/bin/env bun
// convert character to fullwidth unicode version

import { $ } from "bun"

function toFullWidth(str) {
	return str
		.replace(/[!-~]/g, ch => String.fromCharCode(ch.charCodeAt(0) + 0xFEE0))
		.replace(/ /g, '　')
}

const ch = process.argv[2]

if (ch) {
	const ch2 = toFullWidth(ch)
	await $`printf '%s' "${ch2}" | pbcopy`
	console.log(ch2)
}
