#!/bin/sh
# get id3 tags with ffmpeg

help() {
	echo "Get id3 tags"
	echo ""
	echo "USAGE"
	echo "    $ id3 test.mp3"
	echo "    $ id3 artist test.mp3"
	echo "    $ id3 year test.mp3"
}

if [ $# = 1 ]; then
	file=$1
elif [ $# = 2 ]; then
	tag=$1
	file=$2
fi

# https://gist.github.com/eyecatchup/0757b3d8b989fe433979db2ea7d95a01
# https://askubuntu.com/a/1284775/1543361
ffinfo=$(ffprobe -hide_banner -i "$file" 2>&1 | sed -n '/Duration:/q;p')

gettag() {
	echo "$ffinfo" \
		| grep -E "^\s*$1\s*\:\s.*$" \
		| awk -F ': ' '{print $2}'
}

title=$(gettag "title")
artist=$(gettag "artist")
album_artist=$(gettag "album_artist")
composer=$(gettag "composer")
album=$(gettag "album")
track=$(gettag "track")
date=$(gettag "date")
disc=$(gettag "disc")
compilation=$(gettag "compilation")
genre=$(gettag "genre")
grouping=$(gettag "grouping")
comment=$(gettag "comment")

printall() {
	[ -n "$title" ] && echo "title: $title"
	[ -n "$artist" ] && echo "artist: $artist"
	[ -n "$album_artist" ] && echo "album_artist: $album_artist"
	[ -n "$composer" ] && echo "composer: $composer"
	[ -n "$album" ] && echo "album: $album"
	[ -n "$date" ] && echo "date: $date"
	[ -n "$track" ] && echo "track: $track"
	[ -n "$disc" ] && echo "disc: $disc"
	[ -n "$compilation" ] && echo "compilation: $compilation"
	[ -n "$genre" ] && echo "genre: $genre"
	[ -n "$grouping" ] && echo "grouping: $grouping"
	[ -n "$comment" ] && echo "comment: $comment"
}

if [ -z "$tag" ]; then
	printall
	exit
fi

case $tag in
	title)        echo "$title" ;;
	album)        echo "$album" ;;
	artist)       echo "$artist" ;;
	album_artist) echo "$album_artist" ;;
	composer)     echo "$composer" ;;
	date)         echo "$date" ;;
	track)        echo "$track" ;;
	disc)         echo "$disc" ;;
	genre)        echo "$genre" ;;
	grouping)     echo "$grouping" ;;
	comment)      echo "$comment" ;;
	compilation)  echo "$compilation" ;;
esac
