#!/usr/bin/env bun
// merge subtitles into video

import * as fs from "node:fs/promises"
import * as path from "node:path"
import { $ } from "bun"

const HELP = `
Search for {name}.{lang}.srt and embed subtitles to video.

USAGE
  $ mergesubs <vid>
`.trim()

const file = process.argv[2]

if (!file || !await Bun.file(file).exists()) {
	console.log(HELP)
	process.exit()
}

const ext = path.extname(file)
const name = path.basename(file, ext)
const dest = `${name}.subbed${ext}`
const regex = new RegExp(`^${name}\\.(?<lang>.+?)\\.srt$`)
const langs = []

for (const file of await fs.readdir(".")) {
	const match = file.match(regex)
	if (!match) continue
	langs.push(match.groups["lang"])
}

if (langs.length <= 0) {
	process.exit()
}

const inputArgs = [
	"-i", file,
]

const mapArgs = [
	"-map", "0",
]

const metaArgs = []

langs.forEach((lang, i) => {
	inputArgs.push("-i", `${name}.${lang}.srt`)
	mapArgs.push("-map", `${i + 1}`)
	metaArgs.push(`-metadata:s:s:${i}`, `language=${lang}`)
})

const args = [
	"-hide_banner",
	...inputArgs,
	...mapArgs,
	"-c:v", "copy",
	"-c:a", "copy",
	"-c:s", "mov_text",
	...metaArgs,
	dest,
]

await $`ffmpeg ${args}`
