#!/bin/sh
# compress an image

# TODO: --loseless
# TODO: --output

path="$1"

if [ ! -e "$path" ]
then
	echo "file not found"
	exit 1
fi

ext=$(echo "${path##*.}" | tr '[:upper:]' '[:lower:]')

case "$ext" in
	"jpg"|"jpeg")
		jpegoptim -m 50 "$path"
	;;
	"png")
		pngquant --ext .png -f "$path"
	;;
	*)
		echo "unsupported file type: \"$ext\""
	;;
esac
