#!/bin/sh
# compress an image

# TODO: --loseless
# TODO: --output

help() {
	echo "Compress jpeg / png image file"
	echo ""
	echo "USAGE"
	echo "  $ minimg <file>"
	echo ""
	echo "EXAMPLE"
	echo "  $ minimg yoshi.png"
	echo "  $ minimg fish.jpg"
}

path="$1"

if [ -z "$path" ]
then
	help
	exit 1
fi

if [ ! -e "$path" ]
then
	echo "file not found"
	exit 1
fi

ext=$(echo "${path##*.}" | tr '[:upper:]' '[:lower:]')

case "$ext" in
	"jpg"|"jpeg")
		jpegoptim -m 60 "$path"
	;;
	"png")
		pngquant --ext .png -f "$path"
	;;
	*)
		echo "unsupported file type: \"$ext\""
	;;
esac
