#!/usr/bin/env bun

const to = process.argv[2]

if (!to) {
	process.exit()
}

function gen(limit) {
	const sieve = new Array(limit + 1).fill(true)
	sieve[0] = sieve[1] = false
	for (let i = 2; i * i <= limit; i++) {
		if (sieve[i]) {
			for (let j = i * i; j <= limit; j += i) {
				sieve[j] = false
			}
		}
	}
	return sieve.map((v, i) => v ? i : false).filter(v => v)
}

console.log(gen(Number(to)).join(" "))
