#!/bin/sh
# search image with google lens

file="$1"

if [ ! -f "$file" ]; then
	echo "no file"
	exit 1
fi

. $HOME/.env
tmpfile=$(mktemp)
status=$(curl -o "$tmpfile" -w "%{http_code}" -s -F "file=@$file" -H "Authorization: Bearer $SPACE55_TOKEN" https://space55.xyz/tmp)

if [ "$status" != "200" ]; then
	echo "$status" >&2
	cat "$tmpfile" >&2
	rm "$tmpfile"
	exit 1
fi

url=$(cat "$tmpfile")
rm "$tmpfile"

if [ -n "$url" ]; then
	echo "https://lens.google.com/uploadbyurl?url=$url"
fi

osascript -e "display notification \"Failed to upload image\" with title \"Oh no!\""
