#!/bin/sh
# monitor website status

sites="https://space55.xyz,https://davidmurray.xyz"

for site in $(echo $sites | tr "," " "); do
	if [ -n "$site" ]; then
		response=$(curl -sIL -X GET "$site")
		if echo "$response" | head -n 1 | grep "200" > /dev/null; then
			echo "$site is up!"
		else
			echo "$site is down!"
		fi
	fi
done
