#!/bin/sh
# sync stuff to external harddrive

sync() {
	echo "syncing $1 -> $2"
	rclone sync "$1" "$2" \
		--exclude .DS_Store \
		--progress \
		--verbose \
		--track-renames \
		--human-readable \
		--delete-during \
		--modify-window 2s
}

dest="/Volumes/EXTDISK"

sync ~/Music/Media.localized/Music/ $dest/music/
sync ~/files/img/                   $dest/img/
sync ~/files/videos/                $dest/videos/
sync ~/files/.important/            $dest/porn/
sync ~/files/fonts/                 $dest/fonts/
sync ~/files/film/                  $dest/film/
sync ~/files/tv/                    $dest/tv/
sync ~/files/games/                 $dest/games/
sync ~/files/links/                 $dest/link/
sync ~/files/license/               $dest/license/
sync ~/files/os/                    $dest/os/
