#!/bin/sh
# sync stuff to cloud storage

sync() {
	echo "syncing $1 -> $2"
	rclone sync "$1" "$2" --exclude .DS_Store -P
}

bucket="dropbox"

sync ~/Music/Media.localized/Music/ $bucket:music/
sync ~/files/img/                   $bucket:img/
sync ~/files/videos/                $bucket:videos/
sync ~/files/fonts/                 $bucket:fonts/
sync ~/files/film/                  $bucket:film/
