#!/bin/sh
# sync stuff to external hard drive

sync() {
	echo "syncing $1 -> $2"
	rsync -av --delete --exclude '.DS_Store' $1 $2
}

sync ~/Music/Media.localized/Music/ /Volumes/EXTDISK/music
sync ~/files/film/                  /Volumes/EXTDISK/film
sync ~/files/img/                   /Volumes/EXTDISK/img
sync ~/files/books/                 /Volumes/EXTDISK/books
