#!/bin/sh
# sync stuff to cloud storage

sync() {
	echo "syncing $1 -> $2"
	s3cmd sync \
		-v \
		--no-check-md5 \
		--delete-removed \
		--acl-public \
		--exclude '.DS_Store' \
		"$1" "$2"
}

bucket="s3://tga"

sync ~/Music/Media.localized/Music/ $bucket/music/
sync ~/files/img/                   $bucket/img/
sync ~/files/videos/                $bucket/videos/
sync ~/files/fonts/                 $bucket/fonts/
sync ~/files/film/                  $bucket/film/
sync ~/files/books/                 $bucket/books/
sync ~/files/tv/                    $bucket/tv/
