#!/bin/sh
# sync stuff to external hard drive

sync() {
	echo "syncing $1 -> $2"
	# TODO: rsync is re-copying file names with non ascii character
	rsync -av --delete --exclude '.DS_Store' "$1" "$2"
}

drive="/Volumes/EXTDISK"

sync ~/Music/Media.localized/Music/ $drive/music
sync ~/files/film/                  $drive/film
sync ~/files/img/                   $drive/img
sync ~/files/books/                 $drive/books
sync ~/files/videos/                $drive/videos
sync ~/files/tv/                    $drive/tv
