#!/usr/bin/env bun
// sync www.ts server lib file across projects

import * as os from "os"
import * as path from "path"
import * as fs from "fs/promises"
import * as readline from "node:readline/promises"

const home = os.homedir()

const locations = [
	`${home}/dev/www/www.ts`,
	`${home}/dev/space55.xyz/www.ts`,
	`${home}/dev/coilsprite.com/www.ts`,
	`${home}/dev/davidmurray.xyz/www.ts`,
	`${home}/dev/shrooom.net/www.ts`,
	`${home}/dev/zhuazhuazhua.me/www.ts`,
	`${home}/dev/fff/www.ts`,
	`${home}/dev/triospacedesign.com/www.ts`,
]

async function syncToLatest(paths) {

	const contents = {}
	let newestFile = null
	const pathsToWrite = []

	for (const p of paths) {
		const f = Bun.file(p)
		contents[p] = await f.text()
		if (!newestFile || (f.lastModified > newestFile.lastModified)) {
			newestFile = {
				path: p,
				lastModified: f.lastModified,
			}
		}
	}

	for (const p of paths) {
		if (contents[p] !== contents[newestFile.path]) {
			pathsToWrite.push(p)
		}
	}

	if (pathsToWrite.length === 0) {
		console.log("up to date")
		return
	}

	const rl = readline.createInterface({
		input: process.stdin,
		output: process.stdout,
	})

	const answer = await rl.question(`Sync to ${newestFile.path}? (y/N) `)

	rl.close()

	if (answer !== "y") {
		return
	}

	const content = contents[newestFile.path]

	for (const p of pathsToWrite) {
		console.log(`updating: ${p}`)
		Bun.write(p, content)
	}

}

await syncToLatest(locations)
