#!/bin/sh
# sync stuff to external hard drive

sync() {
	echo "syncing $1 -> $2"
	rsync \
		-av \
		--delete \
		--iconv=utf-8,utf-8-mac \
		--exclude '.DS_Store' \
		"$1" "$2"
}

drive="/Volumes/EXTDISK"

sync ~/Music/Media.localized/Music/ $drive/music
sync ~/files/img/                   $drive/img
sync ~/files/games/                 $drive/games
sync ~/files/videos/                $drive/videos
sync ~/files/fonts/                 $drive/fonts
sync ~/files/film/                  $drive/film
sync ~/files/books/                 $drive/books
sync ~/files/tv/                    $drive/tv
