#!/usr/bin/env bun

import * as path from "path"
import * as readline from "node:readline/promises"

const places = [
	"/Users/tga/dev/space55.xyz/www.ts",
	"/Users/tga/dev/coilsprite.com/www.ts",
	"/Users/tga/dev/davidmurray.xyz/www.ts",
	"/Users/tga/dev/shrooom.net/www.ts",
	"/Users/tga/dev/fff/www.ts",
	"/Users/tga/dev/www/www.ts",
]

let lastFile = null

for (const p of places) {
	const f = Bun.file(p)
	if (lastFile) {
		if (f.lastModified > lastFile.lastModified) {
			lastFile = f
		}
	} else {
		lastFile = f
	}
}

const rl = readline.createInterface({
	input: process.stdin,
	output: process.stdout,
})

const answer = await rl.question(`Sync to ${lastFile.name}? (y/N) `)

rl.close()

if (answer !== "y") {
	process.exit()
}

const content = await lastFile.text()

for (const p of places) {
	console.log("updating ", p)
	Bun.write(p, content)
}
