#!/bin/sh
# host a file to a remote file hosting service

file="$1"

if [ ! -f "$file" ]; then
	echo "no file"
	exit 1
fi

. $HOME/.env
curl -s -F "file=@$file" -H "Authorization: Bearer $SPACE55_TOKEN" https://space55.xyz/tmp
