#!/bin/sh
# create screenshot from youtube video

url=$1
time=$2
out=$3

[ -z "$time" ] && time="00:00:00"
[ -z "$out" ] && out="frame.jpg"

ffmpeg \
	-i "$(yt-dlp --get-url "$url")" \
	-ss "$time" \
	-vframes 1 \
	-q:v 2 \
	"$out"
