#!/bin/sh
# create screenshot from youtube video

url=$1
time=$2
out=$3

if [ -z "$time" ]; then
	time="00:00:00"
fi

if [ -z "$out" ]; then
	out="frame.jpg"
fi

ffmpeg \
	-i "$(yt-dlp --get-url "$url")" \
	-ss "$time" \
	-vframes 1 \
	-q:v 2 \
	"$out"
