#!/bin/sh
# create screenshot from youtube video

url=$1
time=${2:-"00:00:00"}
out=${3:-"frame.jpg"}

ffmpeg \
	-hide_banner \
	-i "$(yt-dlp --get-url "$url" | head -n 1)" \
	-ss "$time" \
	-vframes 1 \
	-q:v 2 \
	"$out"
